name: faladr_server
description: API do projeto FalaDr feita com Dart Frog.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dart_frog: ^1.1.0
  postgres: ^3.0.0
  faladr_shared:
    path: ../shared
  dotenv: ^4.2.0
